spring:
  application:
    name: configuration-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\abd\Downloads\Microservices\configuration-server\src\main\resources\config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"